name: Publish to pub.dev

permissions:
  pull-requests: write
  id-token: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test -v

  health:
    needs: setup
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main

  publish:
    needs: health
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
