name: CI

permissions:
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main

  publish-test:
    needs: health
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage -v
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          flags: unittests
          name: model unit tests
      - run: flutter pub publish --dry-run
